### ISSUE TITLE
Changing line-height misaligns the anchor

### ISSUE THREAD

**Issue by Nekkowe** [zachleat/heading-anchors#3]
Setting the line height on a headline misaligns the mouseover anchor for me, like this:

![image](https://github.com/user-attachments/assets/b5fde1c6-f9a0-4479-9092-c06377c15897)

With a line height of 1.6 on h3, the --ha_offsety becomes 527px instead of 523px there, making the mouseover anchor show up too low. Conversely, a lower line height makes the anchor appear too high up.

**Comment by Nekkowe** [comment]
Ah wait, sorry, I understand now - I'm supposed to style the `h3 + ha-placeholder` in that instance and match the line height there.

I can't test out whether that was the only issue here, because now (for some other reason I can't quite pin down), _every single_ anchor has become misaligned (up and to the left), but that doesn't seem to be related to line height, so I'm closing this issue.

**Comment by zachleat** [comment]
fwiw I do think there is _something_ to be fixed here. There is a small pixel difference on my site in Firefox: https://www.zachleat.com/about/
